StarRocks/docs

quick_start/Deploy.md
update Deploy.md '\\G' to '\G'
=> fix md syntax error : '\\G' to '\G'

TOC.md, table_design/Sort_key.md
add sort key.md in table design
=> add sort key.md in table design

sql-reference/sql-statements/account-management/CREATE USER.md
fix the mistake about  example_role ,also make the sample of passwords are consistent with the document context
=> fix the mistake about  example_role

TOC.md, administration/Backup_and_restore.md, administration/Blacklist.md, administration/Build_in_docker.md, administration/Load_balance.md, administration/Memory_management.md, administration/Profiling.md, administration/Query_management.md, benchmarking/SSB_Benchmarking.md, release_notes/release-1.19.md
update releasenote1.19 and some other docs
=> update releasenote1.19 and some other docs

TOC.md
=> update some mistake in url

TOC.md, sql-reference/sql-functions/array-functions/array_position.md
refer to [this](https://github.com/StarRocks/starrocks/pull/2676)
=> Add english doc for array_position function

quick_start/Data_flow_and_control_flow.md
Signed-off-by: Sida <sida@Sidas-MBP.lan>
=> Fix spelling in data control flow doc

quick_start/Deploy.md, quick_start/Import_and_query.md, quick_start/Test_faq.md
Signed-off-by: Sida <star.0731@163.com>
=> Fix grammar in quick_start docs

administration/Build_in_docker.md
=> Fix typo in docker build instructions

loading/RoutineLoad.md
Signed-off-by: Sida <star.0731@163.com>
resolves #71
=> Update Routine load doc

.github/workflows/buildcheck.yml
add npm run build check action, to prevent docs-site build unsuccessful
=> add buildcheck.yml

.github/workflows/buildcheck.yml
=> npm i -E in actions

TOC.md, sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
=> added CTAS

TOC.md, sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md, sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
=> add Ctas to v2.1

TOC.md, faq/Deploy_faq.md, faq/Exporting_faq.md, faq/Others.md, faq/Sql_faq.md, faq/loading/Broker_load_faq.md, faq/loading/DataX_faq.md, faq/loading/Flink_connector_faq.md, faq/loading/Insert_into_faq.md, faq/loading/Loading_faq.md, faq/loading/Routine_load_faq.md, faq/loading/Spark_load_faq.md, faq/loading/Stream_load_faq.md, sql-reference/sql-functions/array-functions/array_agg.md
add one function: array_agg
update titles of FAQ topics
add others faq and sql faq to the toc
delete spark load and others(under the data ingestion)
=> add a function and update faqs titles and TOC

TOC.md, administration/Cluster_administration.md, faq/Sql_faq.md
add manage a cluster
update sql faq
=> add a new topic and update one topic

TOC.md, administration/Cluster_administration.md, faq/Sql_faq.md, loading/Flink-connector-starrocks.md, using_starrocks/File_manager.md
add file manager
update sql faq
update manage a cluster
update flink connector
=> Add and update

TOC.md, administration/Cluster_administration.md, faq/Sql_faq.md, loading/Flink-connector-starrocks.md, using_starrocks/File_manager.md
add and update the following docs according to the Chinese version:
add file manager
update manage a cluster
update flink connector
update manage a cluster
=> Add and update docs

TOC.md, faq/Others.md
=> add other faq

TOC.md, faq/Others.md
=> update others faq

sql-reference/sql-functions/How to Write Functions Documentation.md
=> Update How to Write Functions Documentation.md

sql-reference/sql-statements/data-definition/HLL.md
https://starrocks.atlassian.net/browse/SR-9774
=> resolve a jira issue

TOC.md, sql-reference/sql-statements/Administration/CREATE FILE.md, sql-reference/sql-statements/Administration/DROP FILE.md, sql-reference/sql-statements/Administration/SHOW FILE.md, using_starrocks/filemanager.md
these docs were removed from the doc center before. Some features still rely on them, so we add them back.
=> add four docs
